name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.13.4

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  image_picker:
  any_image_view:
    path: ..

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
    - assets/svg/
    - assets/lottie/
    - assets/avif/
